languageCode = "en-us"
title = "Opportunities to Serve"
baseurl = "https://ismailivolunteer.netlify.com/"
publishDir = "dist"
relativeURLs = true
canonifyURLs = false

[params]
  description = "Find volunteer opportunities within the community"
	facebookappid = "1852662151661154"
