languageCode = "en-us"
title = "Ismaili Volunteer"
baseurl = "http://ismailivolunteer.netlify.com"
publishDir = "dist"
relativeURLs = true
canonifyURLs = false

[params]
  description = "Find volunteer opportunities within the community"
