languageCode = "en-us"
title = "OpportunitiesToServe"
baseurl = "https://ismailivolunteer.netlify.com"
publishDir = "dist"
relativeURLs = false
canonifyURLs = false

[params]
  description = "Find volunteer opportunities within the community"
	facebookappid = "1852662151661154"
	dateformat = "January 2, 2006"

[outputFormats.jsonified]
	mediaType = "application/json"

[outputs]
  home = [
		"html",
		"jsonified",
	]
